### PR TITLE
Fix/connect event to sport

### LINKED ISSUE #160: Connect event to a sport

### PR DESCRIPTION
**Pull request by susmitabhowmik**
This PR:

- Connects a sport to an event, the sport should be displayed along with event details
- Adds a field for users to enter the number of required participants when creating an event
- Adds validation so that a user can't create an event for a sport that is unavailable at a facility
- Closes #160

### CODE REVIEW

**Comment by marcuspoon2** [comment]
Everything looks good but I have a few comments:

In the facilities.html page, I don't think we need to print out 'Yes' after each sport because they're only listed if the sport's value is 'Yes' (line 28 in facilities.html)

Screen Shot 2021-11-16 at 12 27 08 PM

**Comment by marcuspoon2** [comment]
You can enter in a negative number of spots, but we can change the field type in models.py to PositiveIntegerField. It still allows 0, but will prevent negative numbers: 

`  numberOfPlayers = models.IntegerField("Number of People Needed:")
`
`  numberOfPlayers = models.PositiveIntegerField("Number of People Needed:")
`
Screen Shot 2021-11-16 at 12 30 18 PM

**Comment by susmitabhowmik** [comment]
@marcuspoon2 these are great suggestions, and thanks for catching the negative number of spots! I've implemented your suggestions in this commit: 80e27d1aa0b59f402fbce126a0b5ffa2c95bce0f. Let me know if any other changes should be made, thanks!

**Comment by marcuspoon2** [comment]
changes look good, merging PR

**Pull request merged**
